image: openjdk:12-alpine

stages:
  - deploy-prod
  - deploy-dev
  - lint

.deploy:
  stage: deploy
  before_script:
    - apk add curl
  script:
    - ./gradlew clean jar
    - echo ${AUTOCD_URL}
    - curl -vsSfLX POST -H "Content-Type: multipart/form-data" ${AUTOCD_URL} -F token=${AUTOCD_TOKEN} -F autocd=@build/libs/AutoCD-1.0.jar
  tags:
    - docker-build-runner

deploy-prod:
  stage: deploy-prod
  extends: .deploy
  variables:
    AUTOCD_URL: autocd.cloudiety.de
    AUTOCD_TOKEN: ${PROD_TOKEN}
  only:
    - master

deploy-dev:
  stage: deploy-dev
  extends: .deploy
  variables:
    AUTOCD_URL: autocd-dev.cloudiety.de
    AUTOCD_TOKEN: ${DEV_TOKEN}
  only:
    - develop
